name: 4.1.Afficher _l'environnement

# Définition de la variable d'environnement
env:
  MESSAGE: Ceci est une variable d'environnement

# Définition des jobs
jobs:
  display_env:
    name: "Afficher l'environnement"
    runs-on: ubuntu-latest
    steps:
    - name: Afficher le contenu de la variable d'environnement
      run: |
            echo $MESSAGE