name: 4.1.Afficher _l'environnement
env:
  MESSAGE: "Ceci est une variable d'environnement"

jobs:
  display_env:
    
    runs-on: ubuntu-latest
    steps:
    - name: "Afficher le contenu de la variable d'environnement"
      run: |
        echo $MESSAGE