name: 4.2.Afficher_secret

# Définition des jobs
jobs:
  confidential_data:
    name: Données confidentielles
    runs-on: ubuntu-latest
    steps:
    - name: Afficher la valeur du secret
      env:
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      run: echo "La valeur de SUPER_SECRET est \"$SUPER_SECRET\"."