name: 5.2.groupe de logs
on:
  push:
    branches:
      - main

jobs:
  log_group:
    runs-on: ubuntu-latest
    steps:
      - name: Créer le groupe de log ecole-it
        run: echo "::group::ecole-it"
      - name: Afficher le message dans le groupe de log
        run: echo "hello, ecole-it"
      - name: Fermer le groupe de log ecole-it
        run: echo "::endgroup::"
      - name: Afficher un message en dehors du groupe de log
        run: echo "Ceci n'est pas dans le groupe"
