name: milti_workflows.yaml
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Ceci est mon premier job"

        jobs:
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Ceci est mon dexième job"
          